### ISSUE TITLE
no specific error raised when using a wrong port on a existing host

### ISSUE THREAD

**Issue by pmalhaire** [gaopeiliang/aioetcd3#14]
No specific error raised when using a wrong port on a existing host

Considering this code with no etcd running 

```
async def no_host():
    c_etcd = etcd_client(endpoint="127.0.0.1:2379")
    result = await c_etcd.get('/empty')
    print(result)
```

the result I am getting is 
```
Traceback (most recent call last):
  File "server/util/aio_etcd3.py", line 102, in <module>
    loop.run_until_complete(do())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "server/util/aio_etcd3.py", line 94, in do
    await no_host()
  File "server/util/aio_etcd3.py", line 24, in no_host
    result = await c_etcd.get('/empty')
  File "/usr/local/lib/python3.6/dist-packages/aioetcd3/kv.py", line 49, in grpc_func
    return response(await self.grpc_call(method(self), request, timeout=timeout))
  File "/usr/local/lib/python3.6/dist-packages/aioetcd3/base.py", line 23, in grpc_call
    response = await stub_func(request, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/aiogrpc/channel.py", line 40, in __call__
    return await fut
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Connect Failed"
        debug_error_string = "{"created":"@1533897228.302823022","description":"Failed to create subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2608,"referenced_errors":[{"created":"@1533897228.302820797","description":"Pick Cancelled","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":234,"referenced_errors":[{"created":"@1533897228.302803895","description":"Connect Failed","file":"src/core/ext/filters/client_channel/subchannel.cc","file_line":663,"grpc_status":14,"referenced_errors":[{"created":"@1533897228.302698732","description":"Failed to connect to remote host: OS Error","errno":111,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":202,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:127.0.0.1:2380"}]}]}]}"
>
```

Note if the host does not exist no exception is raised and (None,None) is returned.
Maybe a no host error would help to make the difference with a inexistant key.

**Comment by hubo1016** [comment]
You mean the `get` method does not raise exception, but returns a value? It SHOULD raise the GRPC exception. I'll try your code when I have time.

**Comment by pmalhaire** [comment]
It does return the exception so it's the excpected behaviour.

**Comment by pmalhaire** [comment]
I could reproduce with this code, it's a edge case with an etcd instance running at 127.0.0.1:2379 :

```
from aioetcd3.client import client as etcd_client

import asyncio
import json


async def get_not_existing():
    c_etcd = etcd_client(endpoint="127.0.0.1:2379")
    try:
        result = await c_etcd.get('/empty')
    except Exception as e:
        raise Exception("not connected")

    print("get_not_existing:" + str(result))


async def wrong_port():
    c_etcd = etcd_client(endpoint="127.0.0.1:2380")
    try:
        result = await c_etcd.get('/empty')
        print("wrong port:" + str(result))
    except Exception as e:
        print(e)
    return


async def no_host():
    c_etcd = etcd_client(endpoint="127.0.0.2:2379")
    result = await c_etcd.get('/empty')
    print("no host:" + str(result))


async def do():
    await get_not_existing()
    await wrong_port()
    await no_host()

loop = asyncio.get_event_loop()

loop.run_until_complete(do())
```


```
b15cd7809191% python3 test.py                                                                                                                                                                    /cryptonuage/css [On branch pme/etcd_rebased]
get_not_existing(None, None)
<_Rendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Connect Failed"
        debug_error_string = "{"created":"@1533905225.697226010","description":"Failed to create subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2608,"referenced_errors":[{"created":"@1533905225.697224715","description":"Pick Cancelled","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":234,"referenced_errors":[{"created":"@1533905225.697213755","description":"Connect Failed","file":"src/core/ext/filters/client_channel/subchannel.cc","file_line":663,"grpc_status":14,"referenced_errors":[{"created":"@1533905225.697199798","description":"Failed to connect to remote host: OS Error","errno":111,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":202,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:127.0.0.1:2380"}]}]}]}"
>
no host:(None, None)
```

**Comment by hubo1016** [comment]
@pmalhaire 127.0.0.2 is a valid loopback address. In fact, any IP in 127.0.0.0/8 is a valid loop back address, you can try to ping it or create a TCP connection to it, they are all equivalent to 127.0.0.1.

**Comment by pmalhaire** [comment]
@hubo1016 it makes sense, an example with connection errors will be great to avoid anoying you.
